//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Location
{
    using System;
    using System.Collections.Generic;
    
    public partial class Locataire
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Locataire()
        {
            this.Imobiliers = new HashSet<Imobilier>();
        }
    
        public string Email_l { get; set; }
        public string Nom_l { get; set; }
        public string Tel_l { get; set; }
        public string Etat_l { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Imobilier> Imobiliers { get; set; }
        public virtual Usere Usere { get; set; }
    }
}
