//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Location
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usere
    {
        public string Email { get; set; }
        public string Psw { get; set; }
        public string Etat { get; set; }
    
        public virtual Admine Admine { get; set; }
        public virtual Locataire Locataire { get; set; }
    }
}
