//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Location
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imobilier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Imobilier()
        {
            this.Photos = new HashSet<Photo>();
        }
    
        public string Titre_im { get; set; }
        public Nullable<int> Categ_im { get; set; }
        public string Ville_im { get; set; }
        public string Adresse_im { get; set; }
        public string Description { get; set; }
        public string Locatairee { get; set; }
        public string Etat { get; set; }
        public Nullable<double> Prix { get; set; }
        public Nullable<System.DateTime> Date_Cre { get; set; }
        public Nullable<System.DateTime> Date_edit { get; set; }
        public Nullable<System.DateTime> Date_Class { get; set; }
    
        public virtual Categorie Categorie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Photo> Photos { get; set; }
    }
}
