//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Location
{
    using System;
    using System.Collections.Generic;
    
    public partial class Locatairre
    {
        public string Email_l { get; set; }
        public string Nom_l { get; set; }
        public Nullable<int> Tel_l { get; set; }
        public string Etat_l { get; set; }
    
        public virtual User User { get; set; }
    }
}
